# MiniCPS .travis.yml
#
# NOTE: Commits that have [ci skip] anywhere in the commit messages are ignored by Travis CI.
# NOTE: Validate file using https://lint.travis-ci.org/

# NOTE: When sudo is enabled Travis will use a non docker based infrastructure
# sudo: required

language: python

branches:
  only:
    - master

python:
  - "2.7"

# NOTE: Travis-ci automatically preinstalls
# pytest
# nose
# mock

# NOTE: Travis-ci automatically runs
#
install:
  - pip install -r requirements.txt

# TODO: Add mininet-based tests
script: make tests-travis

# NOTE: https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    on_success: change
    on_failure: always
